version: "3.8"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  
  app:
    build: app
    restart: always
    secrets:
      - db-password
    volumes:
        - ./app/src:/src
    ports:
      - 5000:5000
      - 5678:5678
    networks:
      - backnet
      - frontnet

  app2:
    build: app2
    restart: always
    volumes:
      - ./app2/src:/src
    ports:
      - 6000:6000
      - 5679:5679
    networks:
      - frontnet

  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontnet
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backnet:
  frontnet:
